name:                helayo
version:             0.5
github:              "chchch/sanskrit-alignment"
license:             GPL-3
author:              "Charles Li"
maintainer:          "charles.li@ehess.fr"
copyright:           "2020 Charles Li"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/helayo#readme>

dependencies:
- base >= 4.7 && < 5
- array
- vector
- split
- containers
- align-affine
- regex-pcre-builtin
- parsec
- MissingH
- fasta
- hxt-unicode
- matrix
- transformers
- parallel
- deepseq

# test suite
- random
- tasty
- tasty-hunit

library:
  source-dirs: src
  
# Static build options
# see: https://github.com/commercialhaskell/stack/issues/3420
# and https://github.com/icfpcontest2020/starterkit-haskell/issues/2
executables:
  helayo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
#    - -eventlog
#    - -rtsopts
#    - -with-rtsopts=-N
    - -O2
#    - -fPIC
#    - -static
    - -Wall
#    - -optl-fuse-ld=bfd
#    ld-options: -static -pthread
#    cc-options: -static
    dependencies:
    - helayo

tests:
  helayo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - helayo
